// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateCurrencyService CreateCurrencyService
func CreateCurrencyService() *CurrencyService {
	currencyService := NewCurrencyService()
	return currencyService
}

// wire.go:

var (
	CurrencyServiceSet = wire.NewSet(NewCurrencyService)
)
